const COLORS = {
  BLACK: "#000000",
  RED: "#FF0000",
  GREEN: "#00FF00",
  BLUE: "#0000FF",
  ORANGE: "#FFA500",
  YELLOW: "#FFFF00",
  PURPLE: "#800080",
  WHITE: "#FFFFFF",
};

const MENU_ITEMS = {
  PENCIL: "PENCIL",
  ERASER: "ERASER",
  UNDO: "UNDO",
  REDO: "REDO",
  DOWNLOAD: "DOWNLOAD",
} as const;

export { COLORS, MENU_ITEMS };
